id: P000357
initial_creation_type: ocr
created_at: 14/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W27495
  title: གསོ་རིག་ཉེར་མཁོ་གཅེས་བསྡུས
  author: ''
  volumes:
    2e51700d32a04d9fbcef9e51a1a3b1c8:
      image_group_id: I4745
      title: ''
      volume_number: 1
      total_pages: 512
      base_file: v001.txt
